DROP TABLE IF EXISTS category_game_link CASCADE;
DROP TABLE IF EXISTS borrowed_hist CASCADE;
DROP TABLE IF EXISTS curr_borrowed CASCADE;
DROP TABLE IF EXISTS game_copies CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS publishers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS members CASCADE;
